- platform: cisco_iosxe
  host: 192.168.122.101
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  ssh_config_file: True
  timeout_socket: 5
  timeout_transport: 10
  transport: asyncssh
- platform: cisco_iosxe
  host: 192.168.122.102
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  ssh_config_file: True
  timeout_socket: 5
  timeout_transport: 10
  transport: asyncssh
- platform: cisco_iosxe
  host: 192.168.122.103
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  ssh_config_file: True
  timeout_socket: 5
  timeout_transport: 10
  transport: asyncssh
- device_type: cisco_ios
  host: 192.168.122.104
  username: cisco
  password: cisco
  secret: cisco
  timeout: 10
- device_type: cisco_ios
  host: 192.168.122.105
  username: cisco
  password: cisco
  secret: cisco
  timeout: 10
